// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_7e7OBSv18liu0To9wwUBGv2C5VPlbSc',
    appId: '1:770793498115:web:5f0872345c7809cc531036',
    messagingSenderId: '770793498115',
    projectId: 'loan-85736',
    authDomain: 'loan-85736.firebaseapp.com',
    storageBucket: 'loan-85736.firebasestorage.app',
    measurementId: 'G-EQE6MQ4W96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5SQz4HPb42CPBHDtzTAeYpZjSX7fKBkw',
    appId: '1:770793498115:android:04ff5996b51eeba0531036',
    messagingSenderId: '770793498115',
    projectId: 'loan-85736',
    storageBucket: 'loan-85736.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfhxgAVIvBH1UScg7PgWugKJABFnCDDgw',
    appId: '1:770793498115:ios:55a8efab8938a8e3531036',
    messagingSenderId: '770793498115',
    projectId: 'loan-85736',
    storageBucket: 'loan-85736.firebasestorage.app',
    iosBundleId: 'com.example.loan',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfhxgAVIvBH1UScg7PgWugKJABFnCDDgw',
    appId: '1:770793498115:ios:55a8efab8938a8e3531036',
    messagingSenderId: '770793498115',
    projectId: 'loan-85736',
    storageBucket: 'loan-85736.firebasestorage.app',
    iosBundleId: 'com.example.loan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_7e7OBSv18liu0To9wwUBGv2C5VPlbSc',
    appId: '1:770793498115:web:c2ee26e76862cdbc531036',
    messagingSenderId: '770793498115',
    projectId: 'loan-85736',
    authDomain: 'loan-85736.firebaseapp.com',
    storageBucket: 'loan-85736.firebasestorage.app',
    measurementId: 'G-XQWWENQQP8',
  );

}