# -*- coding: utf-8 -*-
"""One-off generator for app_en.arb / app_ar.arb. Run: python tool/gen_arb.py"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "lib" / "l10n"
ROOT.mkdir(parents=True, exist_ok=True)

# English template (keys -> English)
EN = {
    "@@locale": "en",
    "appTitle": "Loan Track",
    "errorPrefix": "Error: {details}",
    "@errorPrefix": {"placeholders": {"details": {"type": "String"}}},
    "userNotLoggedIn": "You are not signed in",
    "loginWelcomeBack": "Welcome back",
    "loginSubtitle": "Sign in to manage shared expenses",
    "hintPassword": "Password",
    "valPasswordRequired": "Password is required",
    "valPasswordMin6": "Password must be at least 6 characters",
    "forgotPassword": "Forgot password?",
    "signIn": "Sign in",
    "noAccount": "Don't have an account? ",
    "createAccountLink": "Create account",
    "privacyPolicy": "Privacy policy",
    "snackPhoneRequired": "Phone number is required",
    "registerTitle": "Create account",
    "registerSubtitle": "Start managing your group expenses today",
    "hintFullName": "Full name",
    "valNameRequired": "Name is required",
    "hintConfirmPassword": "Confirm password",
    "valPasswordMismatch": "Passwords do not match",
    "createAccountBtn": "Create account",
    "haveAccount": "Already have an account? ",
    "signInLink": "Sign in",
    "profileTitle": "My profile",
    "profileMissing": "Profile could not be loaded",
    "labelPhone": "Phone",
    "labelAuthMethod": "Sign-in method",
    "defaultPasswordBanner": "Your account uses the default password. Please change it now.",
    "privacyRelated": "Privacy policy",
    "privacyRelatedSub": "See how your data is used",
    "changePassword": "Change password",
    "hintCurrentPassword": "Current password",
    "hintNewPassword": "New password",
    "savePassword": "Save password",
    "passwordChangedSnack": "Password updated",
    "labelLanguage": "Language",
    "languageArabic": "Arabic",
    "languageEnglish": "English",
    "groupsTitle": "My groups",
    "groupsSubtitle": "Manage shared expenses",
    "emptyGroupsTitle": "No groups yet",
    "emptyGroupsHint": "Create your first group to get started",
    "newGroupFab": "New group",
    "membersCountLine": "{count} members • {currency}",
    "@membersCountLine": {"placeholders": {"count": {"type": "int"}, "currency": {"type": "String"}}},
    "createGroupTitle": "Create group",
    "groupNameLabel": "Group name",
    "groupNameHint": "e.g. Weekend trip",
    "valGroupNameRequired": "Group name is required",
    "valGroupNameTooLong": "Group name is too long",
    "currencyLabel": "Currency",
    "createGroupBtn": "Create group",
    "notificationsTitle": "Notifications",
    "markAllRead": "Mark all as read",
    "notifEmptyTitle": "No notifications",
    "notifEmptySub": "Nothing new right now",
    "loadMore": "Load more",
    "timeNow": "Just now",
    "timeMinutesAgo": "{count} minutes ago",
    "@timeMinutesAgo": {"placeholders": {"count": {"type": "int"}}},
    "timeHoursAgo": "{count} hours ago",
    "@timeHoursAgo": {"placeholders": {"count": {"type": "int"}}},
    "timeDaysAgo": "{count} days ago",
    "@timeDaysAgo": {"placeholders": {"count": {"type": "int"}}},
    "timeDate": "{day}/{month}/{year}",
    "@timeDate": {"placeholders": {"day": {"type": "int"}, "month": {"type": "int"}, "year": {"type": "int"}}},
    "privacyScreenTitle": "Privacy policy",
    "privacyUpdated": "Last updated: {year}",
    "@privacyUpdated": {"placeholders": {"year": {"type": "int"}}},
    "privacyS1t": "1. Introduction",
    "privacyS1b": "We respect your privacy. This policy explains how we collect, use, and share information when you use the app (groups, transactions, balances, and notifications). By using the app you agree to this policy.",
    "privacyS2t": "2. Data we collect",
    "privacyS2b": "• Account: name, phone or email, and sign-in via identity providers (e.g. Google) when enabled.\n• Groups & transactions: amounts, parties, statuses, and notes you enter.\n• Device & usage: technical identifiers needed to run the service.\n• Notifications: content related to transactions, approvals, and settlements.",
    "privacyS3t": "3. How we use data",
    "privacyS3b": "We use data to run the app, show balances and transactions, send notifications to affected users, improve security and stability, and comply with legal obligations when required.",
    "privacyS4t": "4. Third parties",
    "privacyS4b": "We may rely on providers (hosting, authentication, notifications) to process data under their terms. We do not sell your personal data for marketing.",
    "privacyS5t": "5. Storage & security",
    "privacyS5b": "We apply reasonable technical and organizational measures. No system is 100% secure—use a strong password and do not share your account.",
    "privacyS6t": "6. Retention",
    "privacyS6b": "We keep data while your account is active or as needed to provide the service and meet legal duties. You may request deletion subject to product and legal limits.",
    "privacyS7t": "7. Your rights",
    "privacyS7b": "Depending on your jurisdiction, you may access, correct, delete, or restrict processing. Contact official support channels.",
    "privacyS8t": "8. Updates",
    "privacyS8b": "We may update this policy from time to time. Material changes will be communicated as required by law or the product.",
    "privacyS9t": "9. Contact",
    "privacyS9b": "For privacy questions, contact the official support channel listed in the app or developer page.",
    "routerNotFound": "Page not found: {error}",
    "@routerNotFound": {"placeholders": {"error": {"type": "String"}}},
    "invalidPhone": "Invalid phone number",
    "searchCountryHint": "Search country",
    "mobileHint": "Mobile number",
    "txnNewTitle": "New transaction",
    "txnType": "Type",
    "amountLabel": "Amount",
    "amountHint": "0.00",
    "valAmountRequired": "Amount is required",
    "valAmountInvalid": "Enter a valid amount",
    "amountNegativeHint": "If the amount is negative, creditor and debtor will swap automatically",
    "creditorLabel": "Creditor (lender)",
    "creditorHint": "Current creditor",
    "debtorLabel": "Debtor (borrower)",
    "debtorHint": "Choose debtor",
    "noteLabel": "Note (optional)",
    "noteHint": "Note about this transaction",
    "createTxnBtn": "Create transaction",
    "me": "Me",
    "txnError": "Error: {e}",
    "@txnError": {"placeholders": {"e": {"type": "String"}}},
    "pickDebtorSnack": "Please choose a debtor",
    "selfDebtorSnack": "You cannot choose yourself as debtor",
    "noteTooLongSnack": "Note is too long (max 250 characters)",
    "txnDetailTitle": "Transaction details",
    "labelCreditor": "Creditor",
    "labelDebtor": "Debtor",
    "labelNote": "Note",
    "labelCreatedAt": "Created at",
    "labelApprovedAt": "Approved at",
    "labelRejectedAt": "Rejected at",
    "approve": "Approve",
    "reject": "Reject",
    "debtorOnlyActions": "Only the debtor can approve or reject",
    "roleOwner": "Owner",
    "roleAdmin": "Admin",
    "roleMember": "Member",
    "statusApproved": "Approved",
    "statusRejected": "Rejected",
    "statusPending": "Pending",
    "statusCancelled": "Cancelled",
    "typeLoan": "Loan",
    "typeRepayment": "Repayment",
    "typeCorrection": "Correction",
    "gdTabBalances": "Balances",
    "gdTabTransactions": "Transactions",
    "gdTabAnalysis": "Analysis",
    "gdTabMembers": "Members",
    "gdMembersCount": "{count} members",
    "@gdMembersCount": {"placeholders": {"count": {"type": "int"}}},
    "gdSnackTxAdded": "Transaction added",
    "gdMyBalance": "My balance",
    "gdAllBalances": "Everyone's balances",
    "gdYourBalanceTitle": "Your current balance",
    "gdYourBalanceSubtitle": "A clear summary of your position in this group",
    "gdOwedToYou": "Owed to you",
    "gdYouOweOthers": "You owe others",
    "gdNet": "Net",
    "gdBalancesSection": "Balances",
    "gdNoBalances": "No balances to show yet.",
    "gdReceivableGroup": "Receivable from group",
    "gdPayableGroup": "Payable to group",
    "gdBalanced": "Balanced",
    "gdSettlementMember": "Member settlement • {name}",
    "@gdSettlementMember": {"placeholders": {"name": {"type": "String"}}},
    "gdOwesTo": "Owes to {name}",
    "@gdOwesTo": {"placeholders": {"name": {"type": "String"}}},
    "gdOwedBy": "Owed by {name}",
    "@gdOwedBy": {"placeholders": {"name": {"type": "String"}}},
    "gdNoOpenSettlements": "No open settlements for this member.",
    "gdSummary": "Summary",
    "gdTotalReceivable": "Total receivable: {amount} {currency}",
    "@gdTotalReceivable": {"placeholders": {"amount": {"type": "String"}, "currency": {"type": "String"}}},
    "gdTotalPayable": "Total payable: {amount} {currency}",
    "@gdTotalPayable": {"placeholders": {"amount": {"type": "String"}, "currency": {"type": "String"}}},
    "gdNetLine": "Net: {sign}{amount} {currency}",
    "@gdNetLine": {"placeholders": {"sign": {"type": "String"}, "amount": {"type": "String"}, "currency": {"type": "String"}}},
    "gdProposalExpired": "Proposal expired — you can run discovery again",
    "gdProposalLeftH": "Time left: {h} h {m} min",
    "@gdProposalLeftH": {"placeholders": {"h": {"type": "int"}, "m": {"type": "int"}}},
    "gdProposalLeftM": "Time left: {m} min",
    "@gdProposalLeftM": {"placeholders": {"m": {"type": "int"}}},
    "voteApproved": "Approved",
    "voteRejected": "Rejected",
    "votePending": "Pending",
    "gdCircularTitle": "Circular debt settlement",
    "gdDiscoverySome": "{count} settlement proposal(s) created (12h validity)",
    "@gdDiscoverySome": {"placeholders": {"count": {"type": "int"}}},
    "gdDiscoveryNone": "No new settlement cycles right now",
    "gdDiscover": "Discover",
    "gdSettlementHelp": "Any member can find a debt cycle and create a proposal. Everyone sees it; it expires after 12h if voting is incomplete.",
    "gdProposalLine": "Settlement • {amount} {currency}",
    "@gdProposalLine": {"placeholders": {"amount": {"type": "String"}, "currency": {"type": "String"}}},
    "gdReadOnlyVote": "Read-only — voting is for participants in the cycle",
    "gdReject": "Reject",
    "gdApprove": "Approve",
    "gdAnalysisNoTx": "No approved transactions for monthly analysis (or hidden by your permissions)",
    "gdTxCountMonth": "{count} transactions",
    "@gdTxCountMonth": {"placeholders": {"count": {"type": "int"}}},
    "gdMonthlyTotal": "Month total",
    "gdYouReceived": "You received",
    "gdYouPaid": "You paid",
    "gdNewMember": "New member",
    "gdNoMembers": "No members",
    "gdAddMemberTitle": "Add member",
    "gdMemberNameHint": "Member name",
    "gdPhoneHint": "Phone number",
    "gdCancel": "Cancel",
    "gdAdd": "Add",
    "gdValMemberNameRequired": "Member name is required",
    "gdValMemberNameTooLong": "Member name is too long",
    "gdValPhoneTooLong": "Phone number is too long",
    "gdValPhoneRequired": "Phone number is required",
    "gdMemberAddedOk": "Member added successfully",
    "gdFilterUser": "Filter by user",
    "gdAllUsers": "All users",
    "gdNoTx": "No transactions yet",
    "gdNoTxUser": "No transactions for this user",
    "gdNoTxYou": "No transactions for you right now",
    "gdAutoSettlement": "Auto settlement",
    "gdSettlementTitle": "Settlement",
}

AR = {
    "@@locale": "ar",
    "appTitle": "لون تراك",
    "errorPrefix": "خطأ: {details}",
    "@errorPrefix": {"placeholders": {"details": {"type": "String"}}},
    "userNotLoggedIn": "المستخدم غير مسجل الدخول",
    "loginWelcomeBack": "أهلا بعودتك",
    "loginSubtitle": "سجّل الدخول لإدارة المصروفات الجماعية",
    "hintPassword": "كلمة المرور",
    "valPasswordRequired": "كلمة المرور مطلوبة",
    "valPasswordMin6": "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
    "forgotPassword": "هل نسيت كلمة المرور؟",
    "signIn": "تسجيل الدخول",
    "noAccount": "ليس لديك حساب؟ ",
    "createAccountLink": "إنشاء حساب",
    "privacyPolicy": "سياسة الخصوصية",
    "snackPhoneRequired": "رقم الهاتف مطلوب",
    "registerTitle": "إنشاء حساب",
    "registerSubtitle": "ابدأ إدارة مصروفات مجموعتك اليوم",
    "hintFullName": "الاسم الكامل",
    "valNameRequired": "الاسم مطلوب",
    "hintConfirmPassword": "تأكيد كلمة المرور",
    "valPasswordMismatch": "كلمتا المرور غير متطابقتين",
    "createAccountBtn": "إنشاء الحساب",
    "haveAccount": "لديك حساب بالفعل؟ ",
    "signInLink": "تسجيل الدخول",
    "profileTitle": "ملفي الشخصي",
    "profileMissing": "تعذر العثور على الملف الشخصي",
    "labelPhone": "الهاتف",
    "labelAuthMethod": "طريقة تسجيل الدخول",
    "defaultPasswordBanner": "حسابك يستخدم كلمة المرور الافتراضية. يرجى تغييرها الآن.",
    "privacyRelated": "سياسة الخصوصية",
    "privacyRelatedSub": "اطّلع على كيفية استخدام بياناتك",
    "changePassword": "تغيير كلمة المرور",
    "hintCurrentPassword": "كلمة المرور الحالية",
    "hintNewPassword": "كلمة المرور الجديدة",
    "savePassword": "حفظ كلمة المرور",
    "passwordChangedSnack": "تم تحديث كلمة المرور",
    "labelLanguage": "اللغة",
    "languageArabic": "العربية",
    "languageEnglish": "English",
    "groupsTitle": "مجموعاتي",
    "groupsSubtitle": "إدارة المصروفات الجماعية",
    "emptyGroupsTitle": "لا توجد مجموعات بعد",
    "emptyGroupsHint": "أنشئ أول مجموعة للبدء",
    "newGroupFab": "مجموعة جديدة",
    "membersCountLine": "{count} عضو • {currency}",
    "@membersCountLine": {"placeholders": {"count": {"type": "int"}, "currency": {"type": "String"}}},
    "createGroupTitle": "إنشاء مجموعة",
    "groupNameLabel": "اسم المجموعة",
    "groupNameHint": "مثال: رحلة نهاية الأسبوع",
    "valGroupNameRequired": "اسم المجموعة مطلوب",
    "valGroupNameTooLong": "اسم المجموعة طويل جدا",
    "currencyLabel": "العملة",
    "createGroupBtn": "إنشاء المجموعة",
    "notificationsTitle": "الإشعارات",
    "markAllRead": "تحديد الكل كمقروء",
    "notifEmptyTitle": "لا توجد إشعارات",
    "notifEmptySub": "لا يوجد جديد حاليا",
    "loadMore": "تحميل المزيد",
    "timeNow": "الآن",
    "timeMinutesAgo": "قبل {count} دقيقة",
    "@timeMinutesAgo": {"placeholders": {"count": {"type": "int"}}},
    "timeHoursAgo": "قبل {count} ساعة",
    "@timeHoursAgo": {"placeholders": {"count": {"type": "int"}}},
    "timeDaysAgo": "قبل {count} يوم",
    "@timeDaysAgo": {"placeholders": {"count": {"type": "int"}}},
    "timeDate": "{day}/{month}/{year}",
    "@timeDate": {"placeholders": {"day": {"type": "int"}, "month": {"type": "int"}, "year": {"type": "int"}}},
    "privacyScreenTitle": "سياسة الخصوصية",
    "privacyUpdated": "آخر تحديث: {year}",
    "@privacyUpdated": {"placeholders": {"year": {"type": "int"}}},
    "privacyS1t": "1. مقدمة",
    "privacyS1b": "نلتزم بحماية خصوصيتك. توضح هذه السياسة كيفية جمع واستخدام ومشاركة المعلومات عند استخدام التطبيق (إدارة المجموعات والمعاملات والأرصدة والإشعارات). باستخدامك للتطبيق فإنك توافق على هذه السياسة.",
    "privacyS2t": "2. البيانات التي نجمعها",
    "privacyS2b": "• معلومات الحساب: الاسم، رقم الهاتف أو البريد، وبيانات تسجيل الدخول عبر مزودي الهوية (مثل Google) عند تفعيلهم.\n• بيانات المجموعات والمعاملات: المبالغ، الأطراف، الحالات، والملاحظات التي تُدخلها داخل المجموعات.\n• بيانات الجهاز والاستخدام: معرفات تقنية ضرورية لتشغيل الخدمة (مثل معرف المستخدم في النظام الخلفي).\n• الإشعارات: محتوى الإشعارات المتعلقة بالمعاملات والموافقات والتسويات.",
    "privacyS3t": "3. أساس الاستخدام",
    "privacyS3b": "نستخدم البيانات لتشغيل التطبيق، وعرض الأرصدة والمعاملات، وإرسال الإشعارات للمستخدمين المعنيين، وتحسين الأمان والاستقرار، والامتثال للالتزامات القانونية عند الاقتضاء.",
    "privacyS4t": "4. المشاركة مع أطراف ثالثة",
    "privacyS4b": "قد نعتمد على مزودي خدمات (مثل استضافة البيانات والمصادقة والإشعارات) لمعالجة البيانات نيابةً عنا وفق عقودهم وسياساتهم. لا نبيع بياناتك الشخصية لأطراف ثالثة لأغراض تسويقية.",
    "privacyS5t": "5. التخزين والأمان",
    "privacyS5b": "نتخذ تدابير تقنية وتنظيمية معقولة لحماية البيانات. لا يوجد نظام آمن بنسبة 100٪؛ يرجى استخدام كلمة مرور قوية وعدم مشاركة حسابك.",
    "privacyS6t": "6. الاحتفاظ بالبيانات",
    "privacyS6b": "نحتفظ بالبيانات طالما كان حسابك نشطًا أو حسب الحاجة لتقديم الخدمة والالتزامات القانونية. يمكنك طلب حذف الحساب وفق إمكانيات التطبيق والقانون المعمول به.",
    "privacyS7t": "7. حقوقك",
    "privacyS7b": "حسب القانون المعمول ببلدك، قد يحق لك الوصول إلى بياناتك أو تصحيحها أو حذفها أو تقييد المعالجة. تواصل معنا عبر قنوات الدعم الرسمية للتطبيق.",
    "privacyS8t": "8. التحديثات",
    "privacyS8b": "قد نعدّل هذه السياسة من وقت لآخر. سيتم إشعارك بشكل معقول عند التغييرات الجوهرية عندما يقتضي القانون أو التطبيق ذلك.",
    "privacyS9t": "9. التواصل",
    "privacyS9b": "للاستفسارات المتعلقة بالخصوصية، يرجى التواصل عبر وسيلة الدعم الرسمية المعلنة في التطبيق أو على صفحة المطوّر.",
    "routerNotFound": "الصفحة غير موجودة: {error}",
    "@routerNotFound": {"placeholders": {"error": {"type": "String"}}},
    "invalidPhone": "رقم الهاتف غير صالح",
    "searchCountryHint": "البحث عن دولة",
    "mobileHint": "رقم الجوال",
    "txnNewTitle": "معاملة جديدة",
    "txnType": "النوع",
    "amountLabel": "المبلغ",
    "amountHint": "0.00",
    "valAmountRequired": "المبلغ مطلوب",
    "valAmountInvalid": "أدخل مبلغا صحيحا",
    "amountNegativeHint": "إذا كان المبلغ سالبا سيتم عكس الدائن والمدين تلقائيا",
    "creditorLabel": "الدائن (المقرض)",
    "creditorHint": "الدائن الحالي",
    "debtorLabel": "المدين (المقترض)",
    "debtorHint": "اختر المدين",
    "noteLabel": "ملاحظة (اختياري)",
    "noteHint": "ملاحظة عن سبب المعاملة",
    "createTxnBtn": "إنشاء المعاملة",
    "me": "أنا",
    "txnError": "خطأ: {e}",
    "@txnError": {"placeholders": {"e": {"type": "String"}}},
    "pickDebtorSnack": "يرجى اختيار المدين",
    "selfDebtorSnack": "لا يمكن اختيار نفسك كمدين",
    "noteTooLongSnack": "النص طويل جدا، الحد الأقصى للملاحظة 250 حرف",
    "txnDetailTitle": "تفاصيل المعاملة",
    "labelCreditor": "الدائن",
    "labelDebtor": "المدين",
    "labelNote": "الملاحظة",
    "labelCreatedAt": "تاريخ الإنشاء",
    "labelApprovedAt": "تاريخ الموافقة",
    "labelRejectedAt": "تاريخ الرفض",
    "approve": "موافقة",
    "reject": "رفض",
    "debtorOnlyActions": "الموافقة أو الرفض متاح للمدين فقط",
    "roleOwner": "المالك",
    "roleAdmin": "مشرف",
    "roleMember": "عضو",
    "statusApproved": "موافق",
    "statusRejected": "مرفوض",
    "statusPending": "معلّق",
    "statusCancelled": "ملغي",
    "typeLoan": "قرض",
    "typeRepayment": "سداد",
    "typeCorrection": "تصحيح",
    "gdTabBalances": "الأرصدة",
    "gdTabTransactions": "المعاملات",
    "gdTabAnalysis": "التحليل",
    "gdTabMembers": "الأعضاء",
    "gdMembersCount": "{count} عضو",
    "@gdMembersCount": {"placeholders": {"count": {"type": "int"}}},
    "gdSnackTxAdded": "تمت إضافة المعاملة بنجاح",
    "gdMyBalance": "رصيدي",
    "gdAllBalances": "رصيد كل الأعضاء",
    "gdYourBalanceTitle": "رصيدك الحالي",
    "gdYourBalanceSubtitle": "ملخص واضح لرصيدك الحالي داخل هذه المجموعة",
    "gdOwedToYou": "لك على الناس",
    "gdYouOweOthers": "عليك للناس",
    "gdNet": "الصافي",
    "gdBalancesSection": "الأرصدة",
    "gdNoBalances": "لا توجد أرصدة متاحة حاليا.",
    "gdReceivableGroup": "له على المجموعة",
    "gdPayableGroup": "عليه للمجموعة",
    "gdBalanced": "رصيد متوازن",
    "gdSettlementMember": "تسوية العضو • {name}",
    "@gdSettlementMember": {"placeholders": {"name": {"type": "String"}}},
    "gdOwesTo": "عليه لـ {name}",
    "@gdOwesTo": {"placeholders": {"name": {"type": "String"}}},
    "gdOwedBy": "له على {name}",
    "@gdOwedBy": {"placeholders": {"name": {"type": "String"}}},
    "gdNoOpenSettlements": "لا توجد تسويات مفتوحة لهذا العضو.",
    "gdSummary": "الملخص",
    "gdTotalReceivable": "إجمالي له: {amount} {currency}",
    "@gdTotalReceivable": {"placeholders": {"amount": {"type": "String"}, "currency": {"type": "String"}}},
    "gdTotalPayable": "إجمالي عليه: {amount} {currency}",
    "@gdTotalPayable": {"placeholders": {"amount": {"type": "String"}, "currency": {"type": "String"}}},
    "gdNetLine": "الصافي: {sign}{amount} {currency}",
    "@gdNetLine": {"placeholders": {"sign": {"type": "String"}, "amount": {"type": "String"}, "currency": {"type": "String"}}},
    "gdProposalExpired": "انتهت صلاحية الاقتراح — يمكن إعادة الاكتشاف",
    "gdProposalLeftH": "متبقي: {h} ساعة و {m} دقيقة",
    "@gdProposalLeftH": {"placeholders": {"h": {"type": "int"}, "m": {"type": "int"}}},
    "gdProposalLeftM": "متبقي: {m} دقيقة",
    "@gdProposalLeftM": {"placeholders": {"m": {"type": "int"}}},
    "voteApproved": "موافق",
    "voteRejected": "رافض",
    "votePending": "معلّق",
    "gdCircularTitle": "اقتراح تصفية الديون الدائرية",
    "gdDiscoverySome": "تم إنشاء {count} اقتراح/اقتراحات تسوية (صلاحية 12 ساعة)",
    "@gdDiscoverySome": {"placeholders": {"count": {"type": "int"}}},
    "gdDiscoveryNone": "لا توجد حلقات جديدة للتسوية حاليا",
    "gdDiscover": "اكتشاف",
    "gdSettlementHelp": "أي عضو يمكنه البحث عن حلقة ديون وإنشاء اقتراح. الاقتراح يظهر لجميع الأعضاء وينتهي تلقائياً بعد 12 ساعة إن لم يكتمل التصويت.",
    "gdProposalLine": "اقتراح تسوية • {amount} {currency}",
    "@gdProposalLine": {"placeholders": {"amount": {"type": "String"}, "currency": {"type": "String"}}},
    "gdReadOnlyVote": "للاطلاع فقط — التصويت للأطراف المعنية بالحلقة",
    "gdReject": "رفض",
    "gdApprove": "موافقة",
    "gdAnalysisNoTx": "لا توجد معاملات معتمدة للتحليل الشهري (أو لا تظهر لصلاحياتك الحالية)",
    "gdTxCountMonth": "{count} معاملات",
    "@gdTxCountMonth": {"placeholders": {"count": {"type": "int"}}},
    "gdMonthlyTotal": "إجمالي الشهر",
    "gdYouReceived": "لك",
    "gdYouPaid": "عليك",
    "gdNewMember": "عضو جديد",
    "gdNoMembers": "لا يوجد أعضاء",
    "gdAddMemberTitle": "إضافة عضو جديد",
    "gdMemberNameHint": "اسم العضو",
    "gdPhoneHint": "رقم الهاتف",
    "gdCancel": "إلغاء",
    "gdAdd": "إضافة",
    "gdValMemberNameRequired": "اسم العضو مطلوب",
    "gdValMemberNameTooLong": "اسم العضو طويل جدا",
    "gdValPhoneTooLong": "رقم الهاتف طويل جدا",
    "gdValPhoneRequired": "رقم الهاتف مطلوب",
    "gdMemberAddedOk": "تمت إضافة العضو بنجاح",
    "gdFilterUser": "تصفية حسب المستخدم",
    "gdAllUsers": "كل المستخدمين",
    "gdNoTx": "لا توجد معاملات بعد",
    "gdNoTxUser": "لا توجد معاملات لهذا المستخدم",
    "gdNoTxYou": "لا توجد معاملات تخصك حاليا",
    "gdAutoSettlement": "تسوية تلقائية",
    "gdSettlementTitle": "تسوية",
}

# Ensure keys match
assert set(k for k in EN if not k.startswith("@")) == set(
    k for k in AR if not k.startswith("@")
), "Mismatched keys"

(ROOT / "app_en.arb").write_text(
    json.dumps(EN, ensure_ascii=False, indent=2), encoding="utf-8"
)
(ROOT / "app_ar.arb").write_text(
    json.dumps(AR, ensure_ascii=False, indent=2), encoding="utf-8"
)
print("Wrote", ROOT / "app_en.arb", "and app_ar.arb")
